language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6.8"
  - "6.3"
  - "6"

cache:
  directories:
    - "node_modules"

before_install:
  - travis_wait npm install -g lerna

install:
  - lerna bootstrap

before_script: lerna run build
script: lerna run test
